version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timerecorder-db
    environment:
      POSTGRES_DB: timerecorder
      POSTGRES_USER: timerecorder
      POSTGRES_PASSWORD: timerecorder123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - timerecorder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timerecorder -d timerecorder"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timerecorder-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timerecorder
      SPRING_DATASOURCE_USERNAME: timerecorder
      SPRING_DATASOURCE_PASSWORD: timerecorder123
    networks:
      - timerecorder-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  timerecorder-network:
    driver: bridge